"""before seed

Revision ID: 0d1b4a735f47
Revises: d49baa024de8
Create Date: 2026-04-26 22:01:14.005591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1b4a735f47'
down_revision: Union[str, Sequence[str], None] = 'd49baa024de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('refresh_tokens', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=False))
    op.add_column('employees', sa.Column('refresh_tokens', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'refresh_tokens')
    op.drop_column('customers', 'refresh_tokens')
    # ### end Alembic commands ###
