"""assigned units in employee

Revision ID: 322a40825bec
Revises: e737fa493a1f
Create Date: 2026-05-08 22:37:58.131090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322a40825bec'
down_revision: Union[str, Sequence[str], None] = 'e737fa493a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('assigned_units', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'assigned_units')
    # ### end Alembic commands ###
