"""form data

Revision ID: 49131c0c0746
Revises: ae0a5def5680
Create Date: 2026-04-28 00:07:52.527622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49131c0c0746'
down_revision: Union[str, Sequence[str], None] = 'ae0a5def5680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('forms', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('forms', sa.Column('submitter_type', sa.ARRAY(sa.String(length=64)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'submitter_type')
    op.drop_column('forms', 'is_archived')
    op.drop_column('forms', 'is_active')
    # ### end Alembic commands ###
