"""form submittion and exams

Revision ID: 4c61b854af88
Revises: 322a40825bec
Create Date: 2026-05-13 22:36:54.911202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c61b854af88'
down_revision: Union[str, Sequence[str], None] = '322a40825bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
    op.add_column('forms', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('forms', sa.Column('results_revealed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('forms', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.alter_column('forms', 'type',
               existing_type=sa.VARCHAR(length=64),
               server_default='questionnaire',
               type_=sa.String(length=32),
               nullable=False)
    op.create_index('ix_forms_org_active_archived', 'forms', ['organisation_id', 'is_active', 'is_archived'], unique=False)
    op.create_index(op.f('ix_forms_public_token'), 'forms', ['public_token'], unique=True)
    op.add_column('submissions', sa.Column('status', sa.String(length=16), server_default='in_progress', nullable=False))
    op.add_column('submissions', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('submissions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('submissions', sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('submissions', sa.Column('results_revealed', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.create_index('ix_submissions_form_customer_status', 'submissions', ['form_id', 'customer_id', 'status'], unique=False)
    op.create_index('ix_submissions_form_user_status', 'submissions', ['form_id', 'user_id', 'status'], unique=False)
    op.create_index('uq_submissions_one_open_customer', 'submissions', ['form_id', 'customer_id'], unique=True, postgresql_where=sa.text("status = 'in_progress' AND customer_id IS NOT NULL"))
    op.create_index('uq_submissions_one_open_user', 'submissions', ['form_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'in_progress' AND user_id IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_submissions_one_open_user', table_name='submissions', postgresql_where=sa.text("status = 'in_progress' AND user_id IS NOT NULL"))
    op.drop_index('uq_submissions_one_open_customer', table_name='submissions', postgresql_where=sa.text("status = 'in_progress' AND customer_id IS NOT NULL"))
    op.drop_index('ix_submissions_form_user_status', table_name='submissions')
    op.drop_index('ix_submissions_form_customer_status', table_name='submissions')
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_column('submissions', 'results_revealed')
    op.drop_column('submissions', 'attempt_number')
    op.drop_column('submissions', 'expires_at')
    op.drop_column('submissions', 'started_at')
    op.drop_column('submissions', 'status')
    op.drop_index(op.f('ix_forms_public_token'), table_name='forms')
    op.drop_index('ix_forms_org_active_archived', table_name='forms')
    op.alter_column('forms', 'type',
               existing_type=sa.String(length=32),
               server_default=None,
               type_=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('forms', 'public_token')
    op.drop_column('forms', 'results_revealed')
    op.drop_column('forms', 'max_attempts')
    op.drop_column('forms', 'time_limit_minutes')
    # ### end Alembic commands ###
