"""add form organisation and units assigne

Revision ID: e737fa493a1f
Revises: ed62c5095774
Create Date: 2026-05-05 19:52:58.973260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e737fa493a1f'
down_revision: Union[str, Sequence[str], None] = 'ed62c5095774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('organisation_id', sa.Integer(), nullable=False))
    op.add_column('forms', sa.Column('assigned_to_units', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_foreign_key(None, 'forms', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'assigned_to_units')
    op.drop_column('forms', 'organisation_id')
    # ### end Alembic commands ###
