"""form answering

Revision ID: ed62c5095774
Revises: 49131c0c0746
Create Date: 2026-04-28 00:29:30.804431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed62c5095774'
down_revision: Union[str, Sequence[str], None] = '49131c0c0746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('options', sa.ARRAY(sa.String(length=255)), nullable=True))
    op.alter_column('forms', 'submitter_type',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=64)),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forms', 'submitter_type',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=64)),
               nullable=True)
    op.drop_column('form_fields', 'options')
    # ### end Alembic commands ###
